[project]
name = "pac-man-prep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anton Dudnik", email = "anton.dudnik@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flake8>=7.3.0",
    "mazegenerator",
    "mypy>=2.3.1",
    "pydantic>=2.13.5",
    "pygame>=2.6.1",
]

[project.scripts]
pac-man-prep = "pac_man_prep:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["pacman*"]

[tool.flake8]
max-line-length = 100
ignore = ["E402"]

[tool.uv.sources]
mazegenerator = { path = "assets/mazegenerator-2.1.0-py3-none-any.whl" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

